# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu-14.10-vmware-xen"

  # config.vm.network :forwarded_port, guest: 80, host: 8080
  # config.vm.network :private_network, ip: "192.168.77.2"

  # config.vm.synced_folder "/tmp/mirage-vagrant-vms", "/host", type: "nfs"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "vmware_fusion" do |v|
    # Enable hardware virtualization in vmware fusion
    v.vmx["vhv.enable"] = "TRUE"
    # Maybe needed if we want to do stuff with KVM
    v.vmx["vcpu.hotadd"] = "FALSE"
    # Setup CPU and RAM
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "2"
  end

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
  end

  config.vm.provision "shell", path: "../scripts/packages.sh"
  config.vm.provision "shell", path: "../scripts/xen.sh"
  config.vm.provision "shell", path: "../scripts/networking.sh"
  config.vm.provision "shell", path: "../scripts/opam.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/mirage.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/finish.sh"

end
